import js from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import globals from 'globals';
import eslintConfigPrettier from 'eslint-config-prettier';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import { defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';

// Composes the plugins eslint-config-next bundles, plus typescript-eslint,
// rather than extending the preset wholesale — so each rule set is visible and
// tunable here. Source is TypeScript-only (`allowJs` is false); the js/mjs globs
// remain for config files and the scripts/ folder.
const eslintConfig = defineConfig([
	globalIgnores([
		// Default ignores of eslint-config-next:
		'.next/**',
		'out/**',
		'build/**',
		'next-env.d.ts',
		// `.next/**` is root-anchored, so it misses build output nested inside
		// git worktrees (.claude/worktrees/*/.next). Those hold their own full
		// .next/, and ESLint OOMs trying to parse the generated bundles.
		'**/.next/**',
		// A worktree is a second full checkout of this repo, so without this
		// every source file is linted once per worktree and each finding is
		// reported N+1 times. The worktree lints itself when it is the cwd.
		'.claude/**',
		// Generated by `npm run typegen` — never hand-edited, and 500KB+, which
		// is large enough that Babel deoptimises its own code generator on it.
		'sanity.types.ts',
		// Generated by `npm run generate:groq` from src/lib/routes.ts.
		'src/sanity/lib/groq-constants.generated.ts',
	]),

	js.configs.recommended, // base JS correctness (no-undef, no-unused-vars, ...)
	react.configs.flat.recommended,
	react.configs.flat['jsx-runtime'], // React 19 / new JSX transform — no `import React`
	jsxA11y.flatConfigs.recommended,
	nextPlugin.configs['core-web-vitals'],

	{
		// react-hooks v7 ships only legacy (eslintrc) configs, so register the
		// plugin manually and apply its recommended rules in flat form.
		files: ['**/*.{js,jsx,mjs,cjs,ts,mts,tsx}'],
		plugins: { 'react-hooks': reactHooks },
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: { ...globals.browser, ...globals.node },
			parserOptions: { ecmaFeatures: { jsx: true } },
		},
		settings: { react: { version: 'detect' } },
		rules: {
			...reactHooks.configs.recommended.rules,
			'react/prop-types': 'off',
			// styled-jsx: `<style jsx>` / `<style jsx global>` are valid here.
			'react/no-unknown-property': ['error', { ignore: ['jsx', 'global'] }],
			// Unused vars warn (don't block commits); ignore the legacy `React`
			// import (unneeded under jsx-runtime) and _-prefixed throwaways.
			'no-unused-vars': [
				'warn',
				{ varsIgnorePattern: '^(React|_)', argsIgnorePattern: '^_' },
			],
		},
	},

	// TypeScript files: parse with the TS parser and swap the base unused-vars
	// rule for its TS-aware counterpart (leaving both on double-reports).
	{
		files: ['**/*.{ts,mts,tsx}'],
		extends: [tseslint.configs.recommended],
		rules: {
			'no-unused-vars': 'off',
			'@typescript-eslint/no-unused-vars': [
				'warn',
				{ varsIgnorePattern: '^(React|_)', argsIgnorePattern: '^_' },
			],
			// `unknown` is the correct type for Sanity's useFormValue() and for
			// catch bindings; casting at the boundary is the intended pattern.
			'@typescript-eslint/no-explicit-any': 'warn',
			// These three ship as `warn` in react-hooks' recommended set, and
			// `lint` has no --max-warnings, so they gated nothing — while
			// next.config.mjs leans on this rule set as the argument that
			// `reactCompiler: true` is safe. The last two are exactly the
			// "the compiler cannot safely handle this construct" signals, so a
			// real bail-out would have scrolled past as warning #106.
			// --max-warnings=0 is not reachable: 82 of the existing warnings are
			// the deliberate no-explicit-any above.
			'react-hooks/exhaustive-deps': 'error',
			'react-hooks/incompatible-library': 'error',
			'react-hooks/unsupported-syntax': 'error',
			// Declaration merging into `sanity`'s option interfaces needs an empty
			// interface that extends — that IS the mechanism. The rule ships this
			// option for exactly the case, so it belongs here rather than as a
			// disable comment in every file that augments a module.
			'@typescript-eslint/no-empty-object-type': [
				'error',
				{ allowInterfaces: 'with-single-extends' },
			],
		},
	},

	// Member data has no row-level security: the database will serve any
	// member's rows to any query. So the client and the drivers are importable
	// only inside src/lib/member/, where every read is written to scope itself,
	// and one directory is what a review has to check.
	{
		files: ['**/*.{ts,mts,tsx}'],
		ignores: ['src/lib/member/**'],
		rules: {
			'no-restricted-imports': [
				'error',
				{
					patterns: [
						{
							// ./auth too: its internal adapter reads any member's rows.
							group: [
								'@/lib/member/db',
								'**/lib/member/db',
								'@/lib/member/auth',
								'**/lib/member/auth',
							],
							message:
								'Read member data through a function in src/lib/member/ that scopes the query, not through the client or the auth instance.',
						},
						{
							group: [
								'drizzle-orm',
								'drizzle-orm/*',
								'@neondatabase/serverless',
								'@electric-sql/pglite',
							],
							message:
								'Database drivers belong in src/lib/member/ only; see the note on its db.ts.',
						},
					],
				},
			],
		},
	},

	eslintConfigPrettier, // must stay LAST — turns off rules that conflict with Prettier
]);

export default eslintConfig;
