import nextVitals from 'eslint-config-next/core-web-vitals';
import { defineConfig, globalIgnores } from 'eslint/config';

const eslintConfig = defineConfig([
	...nextVitals,
	// Override default ignores of eslint-config-next.
	globalIgnores([
		// Default ignores of eslint-config-next:
		'.next/**',
		'out/**',
		'build/**',
		'next-env.d.ts',
		// `.next/**` is root-anchored, so it misses build output nested inside
		// git worktrees (.claude/worktrees/*/.next). Those hold their own full
		// .next/, and ESLint OOMs trying to parse the generated bundles.
		'**/.next/**',
		// A worktree is a second full checkout of this repo, so without this
		// every source file is linted once per worktree and each finding is
		// reported N+1 times. The worktree lints itself when it is the cwd.
		'.claude/**',
		// Generated by `npm run typegen` — never hand-edited, and 500KB+, which
		// is large enough that Babel deoptimises its own code generator on it.
		'sanity.types.ts',
	]),
]);

export default eslintConfig;
